/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/approvals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Approvals of every environment, newest first. Pending ones feed the approval inbox. */
        get: operations["listApprovals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/environments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listEnvironments"];
        put?: never;
        post: operations["createEnvironment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/environments/{env}/approvals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listEnvironmentApprovals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/environments/{env}/approvals/{id}/decide": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["decideApproval"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/environments/{env}/builds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listBuildJobs"];
        put?: never;
        post: operations["submitBuildJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/environments/{env}/builds/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getBuildJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/environments/{env}/builds/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cancelBuildJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/environments/{env}/builds/{id}/log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getBuildJobLog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/environments/{env}/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRules"];
        put?: never;
        post: operations["createRule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/environments/{env}/rules/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateRule"];
        post?: never;
        delete: operations["deleteRule"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/environments/{env}/sandboxes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listSandboxes"];
        put?: never;
        post: operations["createSandbox"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/environments/{env}/sandboxes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSandbox"];
        put?: never;
        post?: never;
        delete: operations["deleteSandbox"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/environments/{env}/sandboxes/{id}/checkpoints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCheckpoints"];
        put?: never;
        /**
         * Create a disk checkpoint
         * @description Stop the sandbox first; checkpoint capture requires a stopped sandbox.
         */
        post: operations["createCheckpoint"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/environments/{env}/sandboxes/{id}/checkpoints/{checkpoint}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteCheckpoint"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/environments/{env}/sandboxes/{id}/checkpoints/{checkpoint}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["restoreCheckpoint"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/environments/{env}/sandboxes/{id}/connections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The sandbox's most recent connections, newest first. The log is kept in memory only. */
        get: operations["listConnections"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/environments/{env}/sandboxes/{id}/fork": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Copy a sandbox into a new one
         * @description Creates a sandbox with the same template and resources and a copy of /workspace, then starts it. Docker state is not copied. A running sandbox is copied while it runs, so files written during the copy may be inconsistent.
         */
        post: operations["forkSandbox"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/environments/{env}/sandboxes/{id}/ports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listPorts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/environments/{env}/sandboxes/{id}/previews/{port}/open": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["openPreview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/environments/{env}/sandboxes/{id}/rebase": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Move a sandbox onto another template
         * @description Copies /workspace into a new VM built from the template, with the template's resources. Docker images, containers and volumes are lost. Tmux sessions end. A running sandbox is stopped for the copy and started again; a stopped one stays stopped. If the rebase fails, the sandbox stays on its old template in the state it was in.
         */
        post: operations["rebaseSandbox"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/environments/{env}/sandboxes/{id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["startSandbox"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/environments/{env}/sandboxes/{id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["stopSandbox"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/environments/{env}/sandboxes/{id}/terminals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Terminals are tmux sessions; attach over a websocket at .../terminals/{name}/attach. */
        get: operations["listTerminals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/environments/{env}/sandboxes/{id}/terminals/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["closeTerminal"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/environments/{env}/secrets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The secrets of an environment. Sandboxes see each name as an environment variable holding its placeholder. */
        get: operations["listSecrets"];
        put?: never;
        post: operations["createSecret"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/environments/{env}/secrets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** @description The name is fixed at creation. Omitting value keeps the stored value. */
        put: operations["updateSecret"];
        post?: never;
        delete: operations["deleteSecret"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/environments/{env}/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listTemplates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/environments/{env}/templates/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTemplate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/environments/{env}/templates/{id}/sandboxes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createTemplateSandbox"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AgentInfo: {
            arch: string;
            version: string;
        };
        ApprovalView: {
            /** Format: int64 */
            attempts: number;
            /** Format: date-time */
            createdAt: string;
            environmentId: string;
            id: string;
            kind: string;
            network?: components["schemas"]["NetworkRequest"];
            ruleId?: string;
            sandboxId?: string;
            /** @enum {string} */
            status: "pending" | "approved" | "denied" | "dismissed";
            subject: string;
            /** Format: date-time */
            updatedAt: string;
        };
        BuildJobLog: {
            text: string;
            truncated: boolean;
        };
        BuildJobSummary: {
            cleanupError?: string;
            cleanupPending: boolean;
            /** Format: date-time */
            createdAt: string;
            environmentId: string;
            error?: string;
            id: string;
            /** @enum {string} */
            status: "queued" | "preparing" | "setting_up" | "exporting" | "ready" | "failed" | "cancelled";
            templateId?: string;
            /** Format: date-time */
            updatedAt: string;
        };
        BuildJobView: {
            cleanupError?: string;
            cleanupPending: boolean;
            /** Format: date-time */
            createdAt: string;
            environmentId: string;
            error?: string;
            id: string;
            source: string;
            /** @enum {string} */
            status: "queued" | "preparing" | "setting_up" | "exporting" | "ready" | "failed" | "cancelled";
            templateId?: string;
            /** Format: date-time */
            updatedAt: string;
        };
        Checkpoint: {
            /** Format: date-time */
            createdAt: string;
            environmentId: string;
            /** Format: int64 */
            generation: number;
            id: string;
            name: string;
            sandboxId: string;
            /** @enum {string} */
            state: "creating" | "ready" | "deleting";
        };
        Conn: {
            /** @description The destination as the sandbox asked for it */
            address: string;
            /** Format: date-time */
            ended?: string;
            error?: string;
            host: string;
            /** Format: int64 */
            id: number;
            /** @description Studio handled the HTTP requests (proxy rules and hosts with secrets) */
            intercepted?: boolean;
            /** Format: int64 */
            port: number;
            /**
             * Format: int64
             * @description Bytes received by the sandbox
             */
            received: number;
            ruleId?: string;
            /**
             * Format: int64
             * @description Bytes sent by the sandbox
             */
            sent: number;
            /**
             * @description Where the host name came from
             * @enum {string}
             */
            source: "tls" | "http" | "dns" | "socks" | "ip";
            /** Format: date-time */
            started: string;
            /** @enum {string} */
            verdict: "pending" | "open" | "allowed" | "denied" | "undecided" | "failed";
        };
        CreateCheckpointInBody: {
            /** @description Human-readable checkpoint name */
            name: string;
        };
        CreateEnvBody: {
            name: string;
        };
        CreateRequest: {
            /** Format: int64 */
            cpus?: number;
            /** Format: int64 */
            dockerMiB?: number;
            /** Format: int64 */
            maxMemoryMiB?: number;
            /** Format: int64 */
            memoryMiB?: number;
            name: string;
            /** Format: int64 */
            workspaceMiB?: number;
        };
        CreateSecretInBody: {
            /** @description Host patterns the value may be sent to, e.g. api.openai.com or *.example.com */
            hosts: string[] | null;
            /** @description Environment variable name sandboxes see, e.g. OPENAI_API_KEY */
            name: string;
            note?: string;
            /** @description The secret value. It is sealed on arrival and never returned. */
            value: string;
        };
        CreateTemplateSandboxInBody: {
            name: string;
        };
        DecideInBody: {
            /**
             * @description allow or deny creates a rule; dismiss only closes the request
             * @enum {string}
             */
            action: "allow" | "deny" | "dismiss";
            /** @description Host pattern the rule covers; empty means the requested host */
            host?: string;
            /** @description Ports the rule covers; omitted means the default ports for the request, empty means any port */
            ports?: number[] | null;
            /**
             * @description Whether the rule covers only the requesting sandbox
             * @default environment
             * @enum {string}
             */
            scope: "sandbox" | "environment";
        };
        Environment: {
            /** Format: date-time */
            createdAt: string;
            id: string;
            name: string;
        };
        ErrorDetail: {
            /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
            location?: string;
            /** @description Error message text */
            message?: string;
            /** @description The value at the given location */
            value?: unknown;
        };
        ErrorModel: {
            /**
             * @description A human-readable explanation specific to this occurrence of the problem.
             * @example Property foo is required but is missing.
             */
            detail?: string;
            /** @description Optional list of individual error details */
            errors?: components["schemas"]["ErrorDetail"][] | null;
            /**
             * Format: uri
             * @description A URI reference that identifies the specific occurrence of the problem.
             * @example https://example.com/error-log/abc123
             */
            instance?: string;
            /**
             * Format: int64
             * @description HTTP status code
             * @example 400
             */
            status?: number;
            /**
             * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
             * @example Bad Request
             */
            title?: string;
            /**
             * Format: uri
             * @description A URI reference to human-readable documentation for the error.
             * @default about:blank
             * @example https://example.com/errors/example
             */
            type: string;
        };
        ForkInBody: {
            /** @description Name of the new sandbox */
            name: string;
        };
        Health: {
            /** @enum {string} */
            status: "ok";
            version: string;
        };
        NetworkRequest: {
            host: string;
            /** @description Suggested host patterns, most specific first */
            patterns: string[] | null;
            /** Format: int64 */
            port: number;
            sandboxName: string;
        };
        PreviewOpenBody: {
            url: string;
        };
        PreviewPort: {
            /** Format: int64 */
            port: number;
            url: string;
        };
        RebaseInBody: {
            /** @description A ready template in the same environment */
            templateId: string;
        };
        Resources: {
            /** Format: int64 */
            cpus: number;
            /** Format: int64 */
            dockerMiB: number;
            /** Format: int64 */
            maxMemoryMiB: number;
            /** Format: int64 */
            memoryMiB: number;
            /** Format: int64 */
            workspaceMiB: number;
        };
        Rule: {
            /** @enum {string} */
            action: "allow" | "proxy" | "caddy" | "deny";
            config: components["schemas"]["RuleConfig"];
            /** Format: date-time */
            createdAt: string;
            environmentId: string;
            /** @description example.com, *.example.com (includes example.com), or an IP address */
            host: string;
            id: string;
            note: string;
            /** @description Empty means any port */
            ports: number[] | null;
            sandboxId?: string;
        };
        RuleConfig: {
            caddyfile?: string;
            headers?: {
                [key: string]: string;
            };
        };
        RuleConfigInput: {
            /** @description caddy rules only: the routes of a Caddy site, in Caddyfile syntax, that handle the requests. reverse_proxy may send secrets upstream in header_up as {secret.NAME}, over HTTPS to hosts the secret is bound to. */
            caddyfile?: string;
            /** @description proxy rules only: headers set on every request, replacing the sandbox's. Values may reference secrets as {secret.NAME}, which are only sent over HTTPS to hosts the secret is bound to. */
            headers?: {
                [key: string]: string;
            };
        };
        RuleInput: {
            /**
             * @description allow passes connections through untouched; proxy lets Studio handle the HTTP requests, to set headers; caddy hands them to a Caddyfile
             * @enum {string}
             */
            action: "allow" | "proxy" | "caddy" | "deny";
            config?: components["schemas"]["RuleConfigInput"];
            /** @description example.com, *.example.com (includes example.com), or an IP address */
            host: string;
            note?: string;
            /** @description Empty or omitted means any port */
            ports?: number[] | null;
            /** @description Limits the rule to one sandbox of this environment */
            sandboxId?: string;
        };
        Secret: {
            /** Format: date-time */
            createdAt: string;
            environmentId: string;
            hosts: string[] | null;
            id: string;
            name: string;
            note: string;
            placeholder: string;
            /** Format: date-time */
            updatedAt: string;
        };
        Session: {
            /** Format: int64 */
            attached: number;
            /** Format: int64 */
            created: number;
            name: string;
            /** Format: int64 */
            windows: number;
        };
        SubmitInBody: {
            /** @description Template specification in YAML */
            source: string;
        };
        TemplateView: {
            /** Format: date-time */
            createdAt: string;
            environmentId: string;
            id: string;
            platform: string;
            resources: components["schemas"]["Resources"];
        };
        UpdateSecretInBody: {
            /** @description Host patterns the value may be sent to */
            hosts: string[] | null;
            note?: string;
            /** @description A new value. Omit it to keep the stored one. */
            value?: string;
        };
        View: {
            agent?: components["schemas"]["AgentInfo"];
            checkpointRestoreSupported: boolean;
            /** Format: int64 */
            cpus: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: int64 */
            dockerMiB: number;
            environmentId: string;
            /** Format: int64 */
            generation: number;
            id: string;
            /** Format: int64 */
            maxMemoryMiB: number;
            /** Format: int64 */
            memoryMiB: number;
            name: string;
            /** @enum {string} */
            status: "absent" | "created" | "starting" | "running" | "draining" | "paused" | "stopped" | "crashed";
            templateId?: string;
            /** Format: int64 */
            workspaceMiB: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listApprovals: {
        parameters: {
            query?: {
                /** @description Statuses to list; all lists every status */
                status?: "pending" | "approved" | "denied" | "dismissed" | "all";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalView"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    listEnvironments: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Environment"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    createEnvironment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEnvBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Environment"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    listEnvironmentApprovals: {
        parameters: {
            query?: {
                /** @description Statuses to list; all lists every status */
                status?: "pending" | "approved" | "denied" | "dismissed" | "all";
            };
            header?: never;
            path: {
                /** @description Environment ID */
                env: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalView"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    decideApproval: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Environment ID */
                env: string;
                /** @description Approval ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecideInBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    listBuildJobs: {
        parameters: {
            query?: {
                /** @description Maximum number of recent build jobs to return */
                limit?: number;
            };
            header?: never;
            path: {
                /** @description Environment ID */
                env: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuildJobSummary"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    submitBuildJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Environment ID */
                env: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitInBody"];
            };
        };
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuildJobView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    getBuildJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Environment ID */
                env: string;
                /** @description Build job ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuildJobView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    cancelBuildJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Environment ID */
                env: string;
                /** @description Build job ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuildJobView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    getBuildJobLog: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Environment ID */
                env: string;
                /** @description Build job ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuildJobLog"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    listRules: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Environment ID */
                env: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rule"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    createRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Environment ID */
                env: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RuleInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rule"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    updateRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Environment ID */
                env: string;
                /** @description Rule ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RuleInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rule"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    deleteRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Environment ID */
                env: string;
                /** @description Rule ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    listSandboxes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Environment ID */
                env: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["View"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    createSandbox: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Environment ID */
                env: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["View"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    getSandbox: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Environment ID */
                env: string;
                /** @description Sandbox ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["View"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    deleteSandbox: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Environment ID */
                env: string;
                /** @description Sandbox ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    listCheckpoints: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Environment ID */
                env: string;
                /** @description Sandbox ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Checkpoint"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    createCheckpoint: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Environment ID */
                env: string;
                /** @description Sandbox ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCheckpointInBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Checkpoint"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    deleteCheckpoint: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Environment ID */
                env: string;
                /** @description Sandbox ID */
                id: string;
                /** @description Checkpoint ID */
                checkpoint: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    restoreCheckpoint: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Environment ID */
                env: string;
                /** @description Sandbox ID */
                id: string;
                /** @description Checkpoint ID */
                checkpoint: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["View"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    listConnections: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Environment ID */
                env: string;
                /** @description Sandbox ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Conn"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    forkSandbox: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Environment ID */
                env: string;
                /** @description Sandbox ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForkInBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["View"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    listPorts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Environment ID */
                env: string;
                /** @description Sandbox ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreviewPort"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    openPreview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Environment ID */
                env: string;
                /** @description Sandbox ID */
                id: string;
                /** @description Preview port */
                port: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreviewOpenBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    rebaseSandbox: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Environment ID */
                env: string;
                /** @description Sandbox ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RebaseInBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["View"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    startSandbox: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Environment ID */
                env: string;
                /** @description Sandbox ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["View"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    stopSandbox: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Environment ID */
                env: string;
                /** @description Sandbox ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["View"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    listTerminals: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Environment ID */
                env: string;
                /** @description Sandbox ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    closeTerminal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Environment ID */
                env: string;
                /** @description Sandbox ID */
                id: string;
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    listSecrets: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Environment ID */
                env: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Secret"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    createSecret: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Environment ID */
                env: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSecretInBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Secret"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    updateSecret: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Environment ID */
                env: string;
                /** @description Secret ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSecretInBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Secret"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    deleteSecret: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Environment ID */
                env: string;
                /** @description Secret ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    listTemplates: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Environment ID */
                env: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateView"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    getTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Environment ID */
                env: string;
                /** @description Template ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    createTemplateSandbox: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Environment ID */
                env: string;
                /** @description Template ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTemplateSandboxInBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["View"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
}
