// Command exec-stream measures runtime.Run stdin and stdout throughput over msb
// exec in one disposable deny-all VM: it pipes random bytes into sha256sum and
// compares digests, then counts bytes read back from head.
package main

import (
	"context"
	"crypto/rand"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"flag"
	"fmt"
	"io"
	"os"
	"strings"
	"time"

	msb "github.com/superradcompany/microsandbox/sdk/go"

	studioruntime "github.com/lukaskoebe/sandbox-studio/internal/runtime"
)

const baseImage = "sandbox-studio-base:dev"

func main() {
	size := flag.Int64("bytes", 100<<20, "bytes to stream in each direction")
	flag.Parse()
	if err := run(*size); err != nil {
		fmt.Fprintln(os.Stderr, "FAIL:", err)
		os.Exit(1)
	}
}

func run(size int64) (retErr error) {
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Minute)
	defer cancel()
	suffix := make([]byte, 6)
	_, _ = rand.Read(suffix)
	owned := studioruntime.OwnedVM{Name: "spike-exec-stream-" + hex.EncodeToString(suffix), Labels: map[string]string{"studio.kind": "spike", "studio.spike": "exec-stream"}}
	rt := studioruntime.New(studioruntime.Options{Image: baseImage})
	vm, err := msb.CreateSandbox(ctx, owned.Name, msb.WithImage(baseImage), msb.WithPullPolicy(msb.PullPolicyNever),
		msb.WithCPUs(1), msb.WithMemory(512), msb.WithMaxMemory(512), msb.WithDetached(), msb.WithLabels(owned.Labels),
		msb.WithNetwork(&msb.NetworkConfig{DefaultEgress: msb.PolicyActionDeny, DefaultIngress: msb.PolicyActionDeny}))
	defer func() {
		cleanup, cancel := context.WithTimeout(context.Background(), time.Minute)
		defer cancel()
		retErr = errors.Join(retErr, rt.RemoveOwned(cleanup, owned))
	}()
	if err != nil {
		return fmt.Errorf("create %s: %w", owned.Name, err)
	}
	if err := vm.Detach(ctx); err != nil {
		return err
	}

	// stdin: random bytes into sha256sum, hashed on the host too.
	input := io.LimitReader(rand.Reader, size)
	hasher := sha256.New()
	var guestSum strings.Builder
	started := time.Now()
	result, err := rt.Run(ctx, owned, studioruntime.RunCommand{
		Path: "/usr/bin/sha256sum", Stdin: io.TeeReader(input, hasher), Stdout: &guestSum, Timeout: 5 * time.Minute,
	}, nil)
	elapsed := time.Since(started)
	if err != nil || result.ExitCode != 0 {
		return fmt.Errorf("stdin run: %+v %w", result, err)
	}
	want := hex.EncodeToString(hasher.Sum(nil))
	if got, _, _ := strings.Cut(guestSum.String(), " "); got != want {
		return fmt.Errorf("stdin digest mismatch: guest %q host %q", got, want)
	}
	fmt.Printf("PASS stdin: %d bytes in %s = %.1f MB/s, sha256 %s\n", size, elapsed.Round(time.Millisecond), float64(size)/elapsed.Seconds()/1e6, want)

	// stdout: guest-generated bytes, counted on the host.
	counter := &countingWriter{}
	started = time.Now()
	result, err = rt.Run(ctx, owned, studioruntime.RunCommand{
		Path: "/usr/bin/head", Args: []string{"-c", fmt.Sprint(size), "/dev/urandom"}, Stdout: counter, Timeout: 5 * time.Minute,
	}, nil)
	elapsed = time.Since(started)
	if err != nil || result.ExitCode != 0 || counter.n != size {
		return fmt.Errorf("stdout run delivered %d of %d bytes: %+v %w", counter.n, size, result, err)
	}
	fmt.Printf("PASS stdout: %d bytes in %s = %.1f MB/s\n", size, elapsed.Round(time.Millisecond), float64(size)/elapsed.Seconds()/1e6)
	return nil
}

type countingWriter struct{ n int64 }

func (c *countingWriter) Write(p []byte) (int, error) {
	c.n += int64(len(p))
	return len(p), nil
}
