/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EEnvRouteImport } from './routes/e.$env'
import { Route as EEnvIndexRouteImport } from './routes/e.$env.index'
import { Route as EEnvBrowserRouteImport } from './routes/e.$env.browser'
import { Route as EEnvBuildsRouteImport } from './routes/e.$env.builds'
import { Route as EEnvGitRouteImport } from './routes/e.$env.git'
import { Route as EEnvMemoryRouteImport } from './routes/e.$env.memory'
import { Route as EEnvNetworkRouteImport } from './routes/e.$env.network'
import { Route as EEnvPersonasRouteImport } from './routes/e.$env.personas'
import { Route as EEnvProvidersRouteImport } from './routes/e.$env.providers'
import { Route as EEnvSecretsRouteImport } from './routes/e.$env.secrets'
import { Route as EEnvSettingsRouteImport } from './routes/e.$env.settings'
import { Route as EEnvSandboxesIdRouteImport } from './routes/e.$env.sandboxes.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EEnvRoute = EEnvRouteImport.update({
  id: '/e/$env',
  path: '/e/$env',
  getParentRoute: () => rootRouteImport,
} as any)
const EEnvIndexRoute = EEnvIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EEnvRoute,
} as any)
const EEnvBrowserRoute = EEnvBrowserRouteImport.update({
  id: '/browser',
  path: '/browser',
  getParentRoute: () => EEnvRoute,
} as any)
const EEnvBuildsRoute = EEnvBuildsRouteImport.update({
  id: '/builds',
  path: '/builds',
  getParentRoute: () => EEnvRoute,
} as any)
const EEnvGitRoute = EEnvGitRouteImport.update({
  id: '/git',
  path: '/git',
  getParentRoute: () => EEnvRoute,
} as any)
const EEnvMemoryRoute = EEnvMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => EEnvRoute,
} as any)
const EEnvNetworkRoute = EEnvNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => EEnvRoute,
} as any)
const EEnvPersonasRoute = EEnvPersonasRouteImport.update({
  id: '/personas',
  path: '/personas',
  getParentRoute: () => EEnvRoute,
} as any)
const EEnvProvidersRoute = EEnvProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => EEnvRoute,
} as any)
const EEnvSecretsRoute = EEnvSecretsRouteImport.update({
  id: '/secrets',
  path: '/secrets',
  getParentRoute: () => EEnvRoute,
} as any)
const EEnvSettingsRoute = EEnvSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => EEnvRoute,
} as any)
const EEnvSandboxesIdRoute = EEnvSandboxesIdRouteImport.update({
  id: '/sandboxes/$id',
  path: '/sandboxes/$id',
  getParentRoute: () => EEnvRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/e/$env': typeof EEnvRouteWithChildren
  '/e/$env/browser': typeof EEnvBrowserRoute
  '/e/$env/builds': typeof EEnvBuildsRoute
  '/e/$env/git': typeof EEnvGitRoute
  '/e/$env/memory': typeof EEnvMemoryRoute
  '/e/$env/network': typeof EEnvNetworkRoute
  '/e/$env/personas': typeof EEnvPersonasRoute
  '/e/$env/providers': typeof EEnvProvidersRoute
  '/e/$env/secrets': typeof EEnvSecretsRoute
  '/e/$env/settings': typeof EEnvSettingsRoute
  '/e/$env/': typeof EEnvIndexRoute
  '/e/$env/sandboxes/$id': typeof EEnvSandboxesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/e/$env/browser': typeof EEnvBrowserRoute
  '/e/$env/builds': typeof EEnvBuildsRoute
  '/e/$env/git': typeof EEnvGitRoute
  '/e/$env/memory': typeof EEnvMemoryRoute
  '/e/$env/network': typeof EEnvNetworkRoute
  '/e/$env/personas': typeof EEnvPersonasRoute
  '/e/$env/providers': typeof EEnvProvidersRoute
  '/e/$env/secrets': typeof EEnvSecretsRoute
  '/e/$env/settings': typeof EEnvSettingsRoute
  '/e/$env': typeof EEnvIndexRoute
  '/e/$env/sandboxes/$id': typeof EEnvSandboxesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/e/$env': typeof EEnvRouteWithChildren
  '/e/$env/browser': typeof EEnvBrowserRoute
  '/e/$env/builds': typeof EEnvBuildsRoute
  '/e/$env/git': typeof EEnvGitRoute
  '/e/$env/memory': typeof EEnvMemoryRoute
  '/e/$env/network': typeof EEnvNetworkRoute
  '/e/$env/personas': typeof EEnvPersonasRoute
  '/e/$env/providers': typeof EEnvProvidersRoute
  '/e/$env/secrets': typeof EEnvSecretsRoute
  '/e/$env/settings': typeof EEnvSettingsRoute
  '/e/$env/': typeof EEnvIndexRoute
  '/e/$env/sandboxes/$id': typeof EEnvSandboxesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/e/$env'
    | '/e/$env/browser'
    | '/e/$env/builds'
    | '/e/$env/git'
    | '/e/$env/memory'
    | '/e/$env/network'
    | '/e/$env/personas'
    | '/e/$env/providers'
    | '/e/$env/secrets'
    | '/e/$env/settings'
    | '/e/$env/'
    | '/e/$env/sandboxes/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/e/$env/browser'
    | '/e/$env/builds'
    | '/e/$env/git'
    | '/e/$env/memory'
    | '/e/$env/network'
    | '/e/$env/personas'
    | '/e/$env/providers'
    | '/e/$env/secrets'
    | '/e/$env/settings'
    | '/e/$env'
    | '/e/$env/sandboxes/$id'
  id:
    | '__root__'
    | '/'
    | '/e/$env'
    | '/e/$env/browser'
    | '/e/$env/builds'
    | '/e/$env/git'
    | '/e/$env/memory'
    | '/e/$env/network'
    | '/e/$env/personas'
    | '/e/$env/providers'
    | '/e/$env/secrets'
    | '/e/$env/settings'
    | '/e/$env/'
    | '/e/$env/sandboxes/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EEnvRoute: typeof EEnvRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e/$env': {
      id: '/e/$env'
      path: '/e/$env'
      fullPath: '/e/$env'
      preLoaderRoute: typeof EEnvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e/$env/': {
      id: '/e/$env/'
      path: '/'
      fullPath: '/e/$env/'
      preLoaderRoute: typeof EEnvIndexRouteImport
      parentRoute: typeof EEnvRoute
    }
    '/e/$env/browser': {
      id: '/e/$env/browser'
      path: '/browser'
      fullPath: '/e/$env/browser'
      preLoaderRoute: typeof EEnvBrowserRouteImport
      parentRoute: typeof EEnvRoute
    }
    '/e/$env/builds': {
      id: '/e/$env/builds'
      path: '/builds'
      fullPath: '/e/$env/builds'
      preLoaderRoute: typeof EEnvBuildsRouteImport
      parentRoute: typeof EEnvRoute
    }
    '/e/$env/git': {
      id: '/e/$env/git'
      path: '/git'
      fullPath: '/e/$env/git'
      preLoaderRoute: typeof EEnvGitRouteImport
      parentRoute: typeof EEnvRoute
    }
    '/e/$env/memory': {
      id: '/e/$env/memory'
      path: '/memory'
      fullPath: '/e/$env/memory'
      preLoaderRoute: typeof EEnvMemoryRouteImport
      parentRoute: typeof EEnvRoute
    }
    '/e/$env/network': {
      id: '/e/$env/network'
      path: '/network'
      fullPath: '/e/$env/network'
      preLoaderRoute: typeof EEnvNetworkRouteImport
      parentRoute: typeof EEnvRoute
    }
    '/e/$env/personas': {
      id: '/e/$env/personas'
      path: '/personas'
      fullPath: '/e/$env/personas'
      preLoaderRoute: typeof EEnvPersonasRouteImport
      parentRoute: typeof EEnvRoute
    }
    '/e/$env/providers': {
      id: '/e/$env/providers'
      path: '/providers'
      fullPath: '/e/$env/providers'
      preLoaderRoute: typeof EEnvProvidersRouteImport
      parentRoute: typeof EEnvRoute
    }
    '/e/$env/secrets': {
      id: '/e/$env/secrets'
      path: '/secrets'
      fullPath: '/e/$env/secrets'
      preLoaderRoute: typeof EEnvSecretsRouteImport
      parentRoute: typeof EEnvRoute
    }
    '/e/$env/settings': {
      id: '/e/$env/settings'
      path: '/settings'
      fullPath: '/e/$env/settings'
      preLoaderRoute: typeof EEnvSettingsRouteImport
      parentRoute: typeof EEnvRoute
    }
    '/e/$env/sandboxes/$id': {
      id: '/e/$env/sandboxes/$id'
      path: '/sandboxes/$id'
      fullPath: '/e/$env/sandboxes/$id'
      preLoaderRoute: typeof EEnvSandboxesIdRouteImport
      parentRoute: typeof EEnvRoute
    }
  }
}

interface EEnvRouteChildren {
  EEnvBrowserRoute: typeof EEnvBrowserRoute
  EEnvBuildsRoute: typeof EEnvBuildsRoute
  EEnvGitRoute: typeof EEnvGitRoute
  EEnvMemoryRoute: typeof EEnvMemoryRoute
  EEnvNetworkRoute: typeof EEnvNetworkRoute
  EEnvPersonasRoute: typeof EEnvPersonasRoute
  EEnvProvidersRoute: typeof EEnvProvidersRoute
  EEnvSecretsRoute: typeof EEnvSecretsRoute
  EEnvSettingsRoute: typeof EEnvSettingsRoute
  EEnvIndexRoute: typeof EEnvIndexRoute
  EEnvSandboxesIdRoute: typeof EEnvSandboxesIdRoute
}

const EEnvRouteChildren: EEnvRouteChildren = {
  EEnvBrowserRoute: EEnvBrowserRoute,
  EEnvBuildsRoute: EEnvBuildsRoute,
  EEnvGitRoute: EEnvGitRoute,
  EEnvMemoryRoute: EEnvMemoryRoute,
  EEnvNetworkRoute: EEnvNetworkRoute,
  EEnvPersonasRoute: EEnvPersonasRoute,
  EEnvProvidersRoute: EEnvProvidersRoute,
  EEnvSecretsRoute: EEnvSecretsRoute,
  EEnvSettingsRoute: EEnvSettingsRoute,
  EEnvIndexRoute: EEnvIndexRoute,
  EEnvSandboxesIdRoute: EEnvSandboxesIdRoute,
}

const EEnvRouteWithChildren = EEnvRoute._addFileChildren(EEnvRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EEnvRoute: EEnvRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
